# @info: on ne peut pas juste surcharger jusqu'au niveau build args
x-common-environment: &x-common-environment
  TZ: ${TZ:-Europe/Paris}

x-common-build-args: &x-common-build-args
  TZ: ${TZ:-Europe/Paris}

x-php-build-args: &x-php-build-args
  <<: *x-common-build-args
  PHP_UID: ${PHP_UID:-1000}
  PHP_GID: ${PHP_GID:-1000}

x-php-common: &x-php-common
  build:
      args:
        <<: *x-php-build-args
      context: .
  environment:
    <<: *x-common-environment
    DB_URL: ${DB_URL}
    SHELL_VERBOSITY: ${SHELL_VERBOSITY:-3}
  networks:
      - symfony
  restart: unless-stopped

services:
    nginx:
        build:
            args:
                <<: *x-common-build-args
                NGINX_UID: ${NGINX_UID:-1000}
                NGINX_GID: ${NGINX_GID:-1000}
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: nginx
        depends_on:
            - php-fpm
            - postgresql
        environment:
          <<: *x-common-environment
        networks:
            - symfony
        ports:
            - "${NGINX_FORWARD_PORT:-80}:80"
        restart: unless-stopped

    # ofelia:
    #     build:
    #         args:
    #            <<: *x-common-build-args
    #         context: .
    #         dockerfile: docker/ofelia/Dockerfile
    #     container_name: ofelia
    #     depends_on:
    #         - nginx
    #         - php-fpm
    #         - postgresql
    #     environment:
    #       <<: *x-common-environment
    #     restart: unless-stopped
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock:ro

    php-cli:
        <<: *x-php-common
        build:
            dockerfile: docker/php/Dockerfile
            target: php-cli
        container_name: php-cli
        restart: no
        scale: 0

    # php-cron:
    #     <<: *x-php-common
    #     build:
    #         dockerfile: docker/php/Dockerfile
    #         target: php-cron
    #     container_name: php-cron
    #     #scale: 0 # @fixme

    php-fpm:
        <<: *x-php-common
        build:
            args:
              <<: *x-php-build-args
            dockerfile: docker/php/Dockerfile
            target: php-fpm
        container_name: php-fpm
        ports:
            - "${PHP_FPM_FORWARD_PORT:-9000}:9000"

    php-supervisor:
        <<: *x-php-common
        build:
            dockerfile: docker/php/Dockerfile
            target: php-supervisor
        container_name: php-supervisor
        ports:
          - "${SUPERVISORCTL_FORWARD_PORT:-9001}:9001"

    postgresql:
        build:
            args:
              <<: *x-common-build-args
            context: .
            dockerfile: docker/postgresql/Dockerfile
        container_name: postgresql
        environment:
          <<: *x-common-environment
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
          interval: 5s
          timeout: 5s
          retries: 5
        networks:
          - symfony
        ports:
          - "${DB_FORWARD_PORT:-5432}:5432"
        restart: unless-stopped
        volumes:
          - ./data/postgresql/postgres:/data/postgres

# @todo: configure and use
volumes:
  postgresql:
    driver: local

networks:
    symfony:
        driver: bridge
