x-php-common-dev: &x-php-common-dev
  volumes:
    - ./app:/var/www/html:readonly
    - ./data/app/var:/var/www/html/app/var
    - ./docker/alpine/rootfs/usr/local/sbin/apk-version:/usr/local/sbin/apk-version:readonly
    - ./docker/php/rootfs/etc/php82/conf.d/00_opcache.ini:/etc/php82/conf.d/00_opcache.ini:readonly
    - ./docker/php/rootfs/etc/php82/conf.d/50_settings.ini:/etc/php82/conf.d/50_settings.ini:readonly
    - ./docker/php/rootfs/usr/local/bin/php-cli-smoke-test:/usr/local/bin/php-cli-smoke-test:readonly

services:
    nginx:
        volumes:
            - ./app:/var/www/html:readonly
            - ./docker/alpine/rootfs/usr/local/sbin/apk-version:/usr/local/sbin/apk-version:readonly
            - ./docker/nginx/rootfs/etc/nginx/templates/:/etc/nginx/templates/:readonly
            - ./docker/nginx/rootfs/usr/local/bin/nginx-reload:/usr/local/bin/nginx-reload:readonly

    # ofelia:
    #     volumes:
    #         - ./docker/ofelia/rootfs/etc/ofelia.conf:/etc/ofelia.conf:ro

    postgresql:
        volumes:
            - ./docker/postgresql/rootfs/usr/local/bin/postgresql-maintenance:/usr/local/bin/postgresql-maintenance:readonly

    php-cli:
        <<: *x-php-common-dev

    # php-cron:
    #     # @see https://github.com/dubiousjim/dcron/issues/13#issuecomment-1406937781
    #     #init: true
    #     volumes:
    #          <<: *x-php-common-dev
    #         # @fixme
    #         - ./docker/php-cron/rootfs/etc/crontabs/root:/etc/crontabs/root

    php-fpm:
        <<: *x-php-common-dev
        volumes:
            - ./docker/php-fpm/rootfs/usr/local/bin/php-fpm-reload:/usr/local/bin/php-fpm-reload:readonly
            - ./docker/php-fpm/rootfs/etc/php82/php-fpm.conf:/etc/php82/php-fpm.conf:readonly

    php-supervisor:
        <<: *x-php-common-dev
        volumes:
            - ./docker/php-supervisor/rootfs/etc/supervisor.d/:/etc/supervisor.d/:readonly
            - ./docker/php-supervisor/rootfs/etc/supervisord.conf:/etc/supervisord.conf:readonly
