services:
    nginx:
        build:
            args:
                - NGINX_UID=${NGINX_UID:-1000}
                - NGINX_GID=${NGINX_GID:-1000}
                - TZ=${TZ:-Europe/Paris}
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: nginx
        depends_on:
            - php-fpm
            - postgresql
        environment:
          TZ: ${TZ:-Europe/Paris}
        networks:
            - symfony
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        restart: unless-stopped

    # ofelia:
    #     build:
    #         args:
    #             - TZ=${TZ:-Europe/Paris}
    #         context: .
    #         dockerfile: docker/ofelia/Dockerfile
    #     container_name: ofelia
    #     depends_on:
    #         - nginx
    #         - php-fpm
    #         - postgresql
    #     environment:
    #       TZ: ${TZ:-Europe/Paris}
    #     restart: unless-stopped
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock:ro

    php-cli:
        build:
            args:
                - PHP_UID=${PHP_UID:-1000}
                - PHP_GID=${PHP_GID:-1000}
                - TZ=${TZ:-Europe/Paris}
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-cli
        container_name: php-cli
        environment:
          DB_URL: ${DB_URL}
          TZ: ${TZ:-Europe/Paris}
        networks:
            - symfony
        restart: no
        scale: 0

    # php-cron:
    #     build:
    #         args:
    #             - PHP_UID=${PHP_UID:-1000}
    #             - PHP_GID=${PHP_GID:-1000}
    #             - TZ=${TZ:-Europe/Paris}
    #         context: .
    #         dockerfile: docker/php/Dockerfile
    #         target: php-cron
    #     container_name: php-cron
    #     environment:
    #       DB_URL: ${DB_URL}
    #       TZ: ${TZ:-Europe/Paris}
    #     networks:
    #         - symfony
    #     restart: unless-stopped
    #     #scale: 0 # @fixme

    php-fpm:
        build:
            args:
                - PHP_UID=${PHP_UID:-1000}
                - PHP_GID=${PHP_GID:-1000}
                - TZ=${TZ:-Europe/Paris}
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-fpm
        container_name: php-fpm
        environment:
          DB_URL: ${DB_URL}
          TZ: ${TZ:-Europe/Paris}
        networks:
            - symfony
        ports:
            - "${FORWARD_PHP_PORT:-9000}:9000"
        restart: unless-stopped

    php-supervisor:
        build:
            args:
                - PHP_UID=${PHP_UID:-1000}
                - PHP_GID=${PHP_GID:-1000}
                - TZ=${TZ:-Europe/Paris}
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-supervisor
        container_name: php-supervisor
        environment:
          DB_URL: ${DB_URL}
          TZ: ${TZ:-Europe/Paris}
        networks:
            - symfony
        ports:
          - "${FORWARD_SUPERVISORCTL_PORT:-9001}:9001"
        restart: unless-stopped

    postgresql:
        build:
            args:
              - TZ=${TZ:-Europe/Paris}
            context: .
            dockerfile: docker/postgresql/Dockerfile
        container_name: postgresql
        environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
          TZ: ${TZ:-Europe/Paris}
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
          interval: 5s
          timeout: 5s
          retries: 5
        networks:
          - symfony
        ports:
          - "${FORWARD_DB_PORT:-5432}:5432"
        restart: unless-stopped
        volumes:
          - ./data/postgresql/postgres:/data/postgres

volumes:
  postgresql:
    driver: local

networks:
    symfony:
        driver: bridge
